server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dasunSenadeera/spring-cloud-config-store-demo
          search-paths:
            - '*service'